version: '3.5'
services:
  spike-client:
    image: spikeproj/spike-client:latest
    ports:
      - '4200:4200'
    env_file:
      - ./env/spike-client.env
    volumes:
      - "${ROOT_PATH}/SpikeDeployment/certs/spike-client/privatekey.pem:/usr/src/app/dist/src/certs/files/privatekey.pem"
      - "${ROOT_PATH}/SpikeDeployment/certs/spike-client/publickey.pem:/usr/src/app/dist/src/certs/files/publickey.pem"
      - "${ROOT_PATH}/SpikeDeployment/certs/spike-client/certificate.pem:/usr/src/app/dist/src/certs/files/certificate.pem"
    restart: always
    depends_on:
      - spike-server
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1gb
        reservations:
          memory: 256mb
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 5

  spike-server:
    image: spikeproj/spike-server:latest
    ports:
      - '3005:3005'
    env_file:
      - ./env/spike-server.env
    volumes:
      - "${ROOT_PATH}/SpikeDeployment/certs/spike-server/privatekey.pem:/usr/src/app/dist/certs/files/privatekey.pem"
      - "${ROOT_PATH}/SpikeDeployment/certs/spike-server/publickey.pem:/usr/src/app/dist/certs/files/publickey.pem"
      - "${ROOT_PATH}/SpikeDeployment/certs/spike-server/certificate.pem:/usr/src/app/dist/certs/files/certificate.pem"
      - "${ROOT_PATH}/SpikeDeployment/certs/spike-server/publickeyofclient.pem:/usr/src/app/dist/certs/files/publickeyofclient.pem"
      - "${ROOT_PATH}/SpikeDeployment/certs/spike-server/publickeyofospike.pem:/usr/src/app/dist/certs/files/publickeyofospike.pem"
    restart: always
    depends_on:
      - redis
      - ospike
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1gb
        reservations:
          memory: 256mb
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass Spike12345678
    ports:
      - '6379:6379'

  ospike:
    image: spikeproj/ospike:latest
    ports:
      - '1338:1338'
    env_file:
      - ./env/ospike.env
    volumes:
      - ${ROOT_PATH}/SpikeDeployment/certs/ospike/privatekey.pem:/usr/src/app/dist/certs/files/privatekey.pem
      - ${ROOT_PATH}/SpikeDeployment/certs/ospike/publickey.pem:/usr/src/app/dist/certs/files/publickey.pem
      - ${ROOT_PATH}/SpikeDeployment/certs/ospike/certificate.pem:/usr/src/app/dist/certs/files/certificate.pem
      - ${ROOT_PATH}/SpikeDeployment/certs/ospike/jwks.json:/usr/src/app/dist/certs/files/jwks.json
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1gb
        reservations:
          memory: 256mb
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
    
  spike-docs:
    image: spikeproj/spike-docs:latest
    ports:
      - 3001:3000
      - 35729:35729
    volumes:
      - ./docs:/app/docs
      - ./website/blog:/app/website/blog
      - ./website/core:/app/website/core
      - ./website/i18n:/app/website/i18n
      - ./website/pages:/app/website/pages
      - ./website/static:/app/website/static
      - ./website/sidebars.json:/app/website/sidebars.json
      - ./website/siteConfig.js:/app/website/siteConfig.js
    working_dir: /app/website
      
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx.crt:/etc/nginx/nginx.crt
      - ./nginx/nginx.key:/etc/nginx/nginx.key
    ports:
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    depends_on:
      - ospike
      - spike-server
      - spike-client
      - spike-docs
    deploy:
      placement:
        constraints: [node.role == manager]
